version: '3.9'

services:
  crud_app_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@2024
      POSTGRES_DB: crud_db
    volumes:
      - crud_app_db:/var/lib/postgresql/data
    ports:
      - '2345:5432'

volumes:
  crud_app_db:
